title: Chantal Shaib # your name (or website title) here
logo: "/images/tiny.jpg?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc. Applied Computing, <br> University of Toronto 
  <br><br>
  Adventures in NLP, Scala, Python, <br>and everything in between. 
  <br><br>
  Quick links:
  <br><br>
  <a href="/about">:wave: About</a> 
  <br>
  <a href="/now">:dart: Now</a> 
  <br>
  <a href="/projects">:wrench: Projects</a> 
  <br>
  <a href="/books">:books: Books</a>
  <br><br>
    
theme: jekyll-theme-minimal
plugins:
  - jemoji
