title: Chantal Shaib # your name (or website title) here
logo: "/images/tiny.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc. Applied Computing, University of Toronto 
  <br><br>
  Adventures in NLP, Scala, Python, and everything in between. 
  
theme: jekyll-theme-minimal
